# Generated by Django 2.2.7 on 2019-11-25 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=1000)),
                ('taken', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('budget', models.IntegerField()),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('already_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hoursamount', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('suppliers', models.ManyToManyField(to='dashboard.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.IntegerField()),
                ('price', models.FloatField()),
                ('satisfied', models.BooleanField(default=False)),
                ('draftId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Draft')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
                ('supplierId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contractss', models.ManyToManyField(to='dashboard.Contract')),
            ],
        ),
    ]
