# Generated by Django 2.2.7 on 2019-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contract_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftitem',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
