# Generated by Django 2.2.7 on 2019-12-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191202_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='suppliers',
        ),
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier')),
            ],
        ),
    ]
