# Generated by Django 2.2.7 on 2019-11-24 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191124_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('taken', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('already_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.TextField(default='Agent', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hoursamount', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('contractId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('SupplierItemList', models.ManyToManyField(to='accounts.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.IntegerField()),
                ('price', models.FloatField()),
                ('satisfied', models.BooleanField(default=False)),
                ('draftId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Draft')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Item')),
                ('supplierId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('Orders', models.ManyToManyField(to='accounts.Contract')),
            ],
        ),
    ]
