# Generated by Django 2.2.7 on 2019-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191124_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
