# Generated by Django 2.2.7 on 2019-11-24 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contract_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
