# Generated by Django 2.2.7 on 2019-11-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supplier_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Orders',
            new_name='contractss',
        ),
    ]
