# Generated by Django 2.2.7 on 2019-11-24 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191124_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
