# Generated by Django 2.2.7 on 2019-11-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_contract_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='draftitem',
            name='draftId',
        ),
        migrations.RemoveField(
            model_name='draftitem',
            name='itemId',
        ),
        migrations.RemoveField(
            model_name='draftitem',
            name='supplierId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='contractId',
        ),
        migrations.RemoveField(
            model_name='workboard',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
        migrations.DeleteModel(
            name='DraftItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='WorkBoard',
        ),
    ]
